language: php

php:
  - 7.0
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction

script:
  - bin/phpspec run -fpretty --verbose
